name: example
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: "3.24.1"

dependencies:
  flutter:
    sdk: flutter
  deriv_chart:
    path: ../
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  pref: ^2.7.1
  flutter_deriv_api:
    git:
      url: https://github.com/deriv-com/flutter-deriv-api.git
      ref: v1.3.0
  win32: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.2

dependency_overrides:
  intl: ^0.20.2

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/symbols/

flutter_intl:
  main_locale: en
  enabled: true
  class_name: ExampleLocalization
