name: deriv_chart
description: A financial charting library for Flutter applications, offering a comprehensive suite of features for technical analysis and trading visualization.
version: 0.4.1
homepage: https://github.com/deriv-com/flutter-chart
repository: https://github.com/deriv-com/flutter-chart

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  collection: ^1.18.0
  deriv_technical_analysis: ^1.1.1
  equatable: ^2.0.5
  intl: ^0.20.2
  json_annotation: ^4.8.0
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  intl_utils: ^2.8.2
  json_serializable: ^6.7.1

flutter:
  fonts:
    - family: QuillIcons
      fonts:
        - asset: assets/fonts/quill_icons.ttf

flutter_intl:
  main_locale: en
  enabled: true
  class_name: ChartLocalization
